// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzmjcvroqelwzpnhcaow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56bWpjdnJvcWVsd3pwbmhjYW93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0Njg3NTIsImV4cCI6MjA3MDA0NDc1Mn0.tTPxxCUoyOReT8LDLOBwNYBCz6Pvjg0N6tgzIfISr4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});